import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/Sidebar";
import "./globals.css";
import Nav from "../components/Nav";
import { TaskProvider } from "@/context/TaskContext";

export const metadata = {
  title: "Tobams Group Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body>
        <TaskProvider>
          <div className={`flex`}>
            <Sidebar />
            <div className="w-[80%] flex flex-col items-center h-screen overflow-y-scroll">
              <div className="w-[95%] ">
                <Nav />
                {children}
              </div>
            </div>
          </div>
        </TaskProvider>
      </body>
    </html>
  );
}
